import { DataSource } from './dataSource';
export interface BlogpostWithoutInternal {
    /**
     * Unique ID of the object, must be generated by the user
     */
    id: string;
    slug: string;
    title: string;
    content: string;
    thumbnail?: Array<DataSource>;
    headerImage?: Array<DataSource>;
}
